name: pswmanager
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  encrypt: ^2.2.0
  json_annotation: ^2.0.0
  file_picker: ^1.3.3
  flutter_launcher_icons: "^0.6.1"
  path_provider: ^0.5.0+1
  password_hash: ^2.0.0

flutter_icons:
  image_path: "assets/key.png" 
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  esys_flutter_share: ^1.0.1

flutter:
  assets:
    - assets/
  uses-material-design: true

  
